# Generated by Django 5.0.1 on 2024-03-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artista', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=17)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='DescricaoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Descrição de Status',
                'verbose_name_plural': 'Descrição de Status',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=2)),
                ('cidades', models.TextField()),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='OrigemDestinoKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('km', models.CharField(blank=True, max_length=255, null=True)),
                ('horas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Origem Destino',
            },
        ),
        migrations.CreateModel(
            name='AgendarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField()),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('comissao', models.CharField(blank=True, max_length=255, null=True)),
                ('producao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_show', models.TextField()),
                ('nome_vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_enviado', models.DateField(blank=True, null=True)),
                ('data_assinado', models.DateField(blank=True, null=True)),
                ('diaria', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
                ('valor_diaria', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_nome_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('custos', models.CharField(blank=True, max_length=255, null=True)),
                ('operacional', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.artista')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.descricaostatus')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.estado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=255)),
                ('data_pagamento', models.DateField(blank=True)),
                ('valor', models.CharField(max_length=255)),
                ('pagamento_status', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.agendarevento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
